# Project Information
site_name: Datawhale 高校联盟
site_description: Datawhale 高校联盟，点亮更多的个体。
site_author: Datawhale AI Club Team
site_url: https://datawhalechina.github.io/ai-club/
strict: false

# Repository
repo_name: "datawhalechina/ai-club"
repo_url: "https://github.com/datawhalechina/ai-club"

# Copyright
copyright: "Copyright &copy; 2022 - 2023 Datawhale AI Club Team"

# Contents
nav:
    - 简介: index.md
    - 关于 Datawhale: About/datawhale.md
    - 成员: 
        - 现有成员: Members/Members-links.md
        - 清华大学: Members/THU.md
        - 浙江大学: Members/ZJU.md
        - 厦门大学: Members/WISER-CLUB.md
        - 闽江学院: Members/MJU.md

theme:
    name: material
    logo: images/small_datawhale_logo.png
    palette:
        - scheme: default # 日间模式
          primary: white # 上方的
          accent: red # 链接等可交互元件的高亮色
          toggle:
              icon: material/weather-night # 图标
              name: 切换至夜间模式 # 鼠标悬浮提示
        - scheme: slate # 夜间模式
          primary: black
          accent: yellow
          toggle:
              icon: material/weather-sunny
              name: 切换至日间模式
    features:
        - navigation.instant #- header.autohide  #自动隐藏
        - announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
        - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
        - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
        - navigation.top # 返回顶部的按钮 在上滑时出现
        - search.suggest # 搜索输入一些字母时推荐补全整个单词
        - search.highlight # 搜索出的文章关键词加入高亮
        - content.code.copy # 代码块右侧复制到剪切板
        #- navigation.expand # 打开Tab时左侧目录全部展开
    language: zh # 一些提示性的文字会变成中文

extra:
    generator: false

plugins:
    - search
    - tags #标签
    - glightbox

markdown_extensions:
    - abbr
    - pymdownx.arithmatex: # MathJax 支持
          generic: true
    - pymdownx.caret
    - pymdownx.mark
    - pymdownx.tilde
    - md_in_html
    - toc:
          permalink: true # 固定标题位置为当前位置
    - pymdownx.highlight: # 代码块高亮
          anchor_linenums: true
          linenums: true # 显示行号
          #auto_title: true # 显示编程语言名称
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences # 代码高亮支持
    - tables
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - admonition
    - pymdownx.details

extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
